name: Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4

            - name: Install bun
              uses: oven-sh/setup-bun@v1

            - name: Install And Build
              run: |
                  bun i
                  bun run build
                  mv build stardbchallenge-new

            - name: Copy New Files
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  source: stardbchallenge-new
                  target: /root/

            - name: Restart Service
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      rm -rf stardbchallenge
                      mv stardbchallenge-new stardbchallenge
                      systemctl restart stardbchallenge
